### ISSUE TITLE
can't reject party invitation when you are not already in a party

### ISSUE THREAD

**Issue by Alys** [HabitRPG/habitica-android#1015]
If you are not in a party and you receive a party invitation, you see the accept and reject buttons. Accept works, but reject does not. When you click reject, you see the error message "Group not found or you don't have access."

The expected behaviour should be that even if the API triggers that message, it shouldn't be shown to the user, and the reject button should work regardless.

Example Loggly error:
```
{"method":"POST","originalUrl":"/api/v4/groups/ae9bf3a2-8050-4253-85ba-14eab6b19e72/quests/reject",
"headers":{"connection":"Keep-Alive","accept-encoding":"gzip","authorization":"Basic ....","host":"habitica.com","max-forwards":"10","user-agent":"Dalvik/2.1.0...","x-api-user":"50adeba6-7184-4a1d-97d4-b08e4effdb46","x-client":"habitica-android","x-forwarded-proto":"https","x-forwarded-port":"443","x-original-host":"habitica.com","sec-websocket-extensions":"","x-original-url":"/api/v4/groups/ae9bf3a2-8050-4253-85ba-14eab6b19e72/quests/reject","x-forwarded-for":"58...:45498","x-arr-ssl":"2048|256|C=GB, S=Greater Manchester, L=Salford, O=COMODO CA Limited, CN=COMODO RSA Domain Validation Secure Server CA|OU=Domain Control Validated, OU=EssentialSSL Wildcard, CN=*.habitica.com","x-arr-log-id":"e7c83786-0071-45a7-a791-4fd31e8bc6cb","content-length":"0"}
,"body":{},
"httpCode":404,
"isHandledError":true,
"timestamp":"2018-08-07T07:36:58.858Z","level":"warn",
"message":"NotFound: Group not found or you don't have access.\n at handler (/usr/src/habitrpg/website/transpiled-babel/controllers/api-v3/quests.js:245:23)\n at <anonymous>\n at process._tickDomainCallback (internal/process/next_tick.js:228:7)"}
```

Related issue: https://github.com/HabitRPG/habitica-android/issues/1014

**Comment by Alys** [comment]
Android app version 1.5 (1980)
