### ISSUE TITLE
Crash after login

### ISSUE THREAD

**Issue by franzejr** [HabitRPG/habitica-android#107]
1. Login
2. Logout.
3. Login
4. It crashes

```
510-3630/com.habitrpg.android.habitica.debug E/AndroidRuntime: FATAL EXCEPTION: Thread-232
                                                                                   Process: com.habitrpg.android.habitica.debug, PID: 3510
                                                                                   android.database.sqlite.SQLiteDoneException
                                                                                       at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
                                                                                       at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:598)
                                                                                       at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
                                                                                       at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
                                                                                       at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:825)
                                                                                       at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:813)
                                                                                       at com.raizlabs.android.dbflow.sql.language.Where.count(Where.java:287)
                                                                                       at com.raizlabs.android.dbflow.sql.language.From.count(From.java:200)
                                                                                       at com.habitrpg.android.habitica.MainActivity.loadAndRemoveOldChecklists(MainActivity.java:342)
                                                                                       at com.habitrpg.android.habitica.MainActivity.access$400(MainActivity.java:68)
                                                                                       at com.habitrpg.android.habitica.MainActivity$4.run(MainActivity.java:272)
                                                                                       at java.lang.Thread.run(Thread.java:818)

```

**Comment by IvanAldrich** [comment]
@franzejr i just got the "cannot rollback"exception, do you have any idea about it ? thx
`android.database.sqlite.SQLiteException: cannot rollback - no transaction is active (code 1)
	at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:548)
	at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
	at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
	at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:522)
	at de.greenrobot.dao.AbstractDao.deleteInTxInternal(AbstractDao.java:576)
	at de.greenrobot.dao.AbstractDao.deleteInTx(AbstractDao.java:587)`
