### ISSUE TITLE
Crash due to: `newCheckListEditText` not found.

### ISSUE THREAD

**Issue by da-h** [HabitRPG/habitica-android#1119]
Hi everyone,

I am experiencing crashes of this app in the following situations:
- pressing the "*new habit*"-Button or the "*new Reward*"-Button. It works, though, for "*New Daily*" and "*New To-Do*".
- pressing an item-label, like the predefined "*Take a short break*".

The log says the following:
```
04-01 22:04:51.920  5705  5705 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@c163a44
04-01 22:04:51.978  5705  5722 E FirebaseInstanceId: Google Play services missing or without correct permission.
04-01 22:04:52.025  5705  5705 I TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
04-01 22:04:52.034  5705  5705 I chatty  : uid=10119(com.habitrpg.android.habitica) identical 1 line
04-01 22:04:52.042  5705  5705 I TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
04-01 22:04:52.161  5705  5705 D AndroidRuntime: Shutting down VM
04-01 22:04:52.162  5705  5705 E AndroidRuntime: FATAL EXCEPTION: main
04-01 22:04:52.162  5705  5705 E AndroidRuntime: Process: com.habitrpg.android.habitica, PID: 5705
04-01 22:04:52.162  5705  5705 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.habitrpg.android.habitica/com.habitrpg.android.habitica.ui.activities.TaskFormActivity}: java.lang.IllegalStateException: View ID 2131297194 for 'newCheckListEditText' not found.
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: Caused by: java.lang.IllegalStateException: View ID 2131297194 for 'newCheckListEditText' not found.
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at com.habitrpg.android.habitica.ui.helpers.g.b(Kotterknife.kt:79)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at com.habitrpg.android.habitica.ui.helpers.g.a(Kotterknife.kt:1)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at com.habitrpg.android.habitica.ui.helpers.g$e.a(Kotterknife.kt:83)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at com.habitrpg.android.habitica.ui.helpers.g$e.a(Unknown Source:2)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at com.habitrpg.android.habitica.ui.helpers.n.a(Kotterknife.kt:106)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at com.habitrpg.android.habitica.ui.activities.TaskFormActivity.v(Unknown Source:8)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at com.habitrpg.android.habitica.ui.activities.TaskFormActivity.onCreate(TaskFormActivity.kt:245)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7144)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7135)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
04-01 22:04:52.162  5705  5705 E AndroidRuntime: 	... 11 more
04-01 22:04:52.369  5705  5747 W CrashlyticsCore: Cannot send reports. Settings are unavailable.
04-01 22:04:52.374  5705  5722 E FirebaseInstanceId: Google Play services missing or without correct permission.
04-01 22:04:52.374  1120  5292 W ActivityManager:   Force finishing activity com.habitrpg.android.habitica/.ui.activities.TaskFormActivity
04-01 22:04:52.379  1120  5292 W ActivityManager:   Force finishing activity com.habitrpg.android.habitica/.ui.activities.MainActivity
04-01 22:04:52.391  1120  1558 I ActivityManager: Showing crash dialog for package com.habitrpg.android.habitica u0
04-01 22:04:52.877  1120  1557 W ActivityManager: Activity pause timeout for ActivityRecord{f443540 u0 com.habitrpg.android.habitica/.ui.activities.TaskFormActivity t166 f}
04-01 22:04:52.921  5705  5765 W FirebaseRemoteConfig: No value of type 'String' exists for parameter key 'sessions_max_length_minutes'.
04-01 22:04:52.921  5705  5744 W FirebaseRemoteConfig: No value of type 'String' exists for parameter key 'sessions_feature_enabled'.
04-01 22:04:52.921  5705  5765 E com.amplitude.api.AmplitudeClient: Invalid API key, make sure your API key is correct in initialize()
04-01 22:04:52.923  5705  5744 W FirebaseRemoteConfig: No value of type 'String' exists for parameter key 'fpr_vc_network_request_sampling_rate'.
04-01 22:04:52.927  5705  5758 W GooglePlayServicesUtil: Google Play Store is missing.

```

My Testsetups so far:
- **AOSP Marshmallow 6.0.1** (compiled the app using API level: Android 23)
- **AOSP Pie 9.0** (compiled the app using API level: Android 28)

In both cases, **no Google Play Services are installed**.

Is the issue related to self-compilaton, the missing google play services or a bug in the code?

Best,
*da-h*

**Comment by da-h** [comment]
Hi,

just a short note:
The problem does not exist in the debug apk.

Best,
*da-h*

**Comment by phillipthelen** [comment]
Hi,

So this was happening with the old task form, but is now fixed with the redesigned one?

**Comment by da-h** [comment]
I feel like there's been a misunderstanding. (Or I misunderstood the correct setup of the build).

To make my setup clear:
- I used the *develop* branch (current state) of the project and compiled all versions
- I did not tried the old task form yet (of the *release* branch)
- the **prod-release apk did** encounter the listed problems
- the **prod-debug apk did not** encounter the listed problems

My quickfix so far:
I used the debug-apk, but removed LeakCanary so that I can use the app without interruptions because of the Heap-Analysis.

**Comment by phillipthelen** [comment]
The error is that `newCheckListEditText` does not exist. Which is not a name that the new task form uses. Can you try pulling from develop again to see if the issue still happens to you? Since the task form was completely rewritten, the original error can't be happening anymore.
