### ISSUE TITLE
Crashes when instabug activity is opened

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-android#121]
```
Fatal Exception: java.lang.NoClassDefFoundError: android.support.v7.internal.view.SupportMenuInflater
   at com.instabug.library.InstabugFeedbackActivity.onViewCreated(InstabugFeedbackActivity.java:123)
   at com.instabug.library.InstabugAnnotationScreen.onCreate(InstabugAnnotationScreen.java:109)
   at com.instabug.library.InstabugFeedbackActivity.onCreate(InstabugFeedbackActivity.java:30)
   at android.app.Activity.performCreate(Activity.java:5451)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
   at android.app.ActivityThread.access$900(ActivityThread.java:175)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:146)
   at android.app.ActivityThread.main(ActivityThread.java:5602)
   at java.lang.reflect.Method.invokeNative(Method.java)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
   at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by toddhodes** [comment]
hi, sorry to bother you.  I'm getting the same thing, from instabug; wrote to them about it, hopefully they'll have some feedback.  but, anyway, did you happen to resolve it somehow?  not seeing diffs.

**Comment by PaoloRotolo** [comment]
I'm having the same issue too.

**Comment by toddhodes** [comment]
solution seems to be 

compile 'com.instabug.library:instabugsupport:1.7.3'

(was pulling in 1.8-SNAPSHOT by default)

**Comment by PaoloRotolo** [comment]
Yes, I've relized it yesterday. instabugsuppprt:1.+ in gradle takes a bugged version.
Thank you anyway.

**Comment by octohub** [comment]
In my case I had the following compile statement:
`compile 'com.instabug.library:instabugsupport:1.7'`
Changed it to:
`compile 'com.instabug.library:instabugsupport:1.7.4'`
And now it's all fixed. You can see their most recent releases [here](http://mvnrepository.com/artifact/com.instabug.library/instabugsupport).
