### ISSUE TITLE
unable to run successful build for local habitica on Google Pixel 2 (or any virtual devices)

### ISSUE THREAD

**Issue by bootymcjudy** [HabitRPG/habitica-android#1880]
After following the instructions from the Readme I was able to successfully build the project but when running getting into an error about invalid application ID,

```
11/18 02:55:21: Launching 'Habitica' on Google Pixel 2 XL.
Install successfully finished in 4 s 72 ms.
$ adb shell am start -n "com.habitrpg.android.habitica.debug/com.habitrpg.android.habitica.ui.activities.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 4407 on device 'google-pixel_2_xl-adb-709KPSL0079518-vALLW7._adb-tls-connect._tcp'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/.habitica.debu: Late-enabling -Xcheck:jni
I/.habitica.debu: Unquickening 12 vdex files!
D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.habitrpg.android.habitica.debug, PID: 4407
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * Invalid application ID. Follow instructions here:                          *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to find your app ID.                                                       *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:7244)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6780)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6697)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * Invalid application ID. Follow instructions here:                          *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to find your app ID.                                                       *
    ******************************************************************************
    
    
        at com.google.android.gms.ads.internal.client.zzee.attachInfo(com.google.android.gms:play-services-ads-lite@@21.2.0:22)
        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@21.2.0:1)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7239)
        	... 10 more
I/Process: Sending signal. PID: 4407 SIG: 9
```

**Comment by Hafizzle** [comment]
Hey @bootymcjudy - 

Currently the Readme does not seems to include a dummy ads Application ID - thank you for providing the error!
In the meantime, you can find test AdMob Id's located here - https://developers.google.com/admob/android/test-ads

 In Habitica\AndroidManifest you can replace the `com.google.android.gms.ads.APPLICATION_ID` value with a dummy/test AdMob ID.

If those IDs don't work, you can also use this ID - `ca-app-pub-3940256099942544~3347511713`

If you have any questions please don't hesitate to ask!
