### ISSUE TITLE
Crash caused by failing foreign constraint.

### ISSUE THREAD

**Issue by vIiRuS** [HabitRPG/habitica-android#471]
Since update 0.0.27 there has been an increase in crashes due to failing foreign key constraints. Unfortunately the crashreports don't include which table/foreignkey caused the problem.

crashlog:

```
Fatal Exception: java.lang.RuntimeException: android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
   at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:75)
Caused by android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787)
   at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(SQLiteConnection.java)
   at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:788)
   at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
   at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
   at com.raizlabs.android.dbflow.sql.SqlUtils.insert(SqlUtils.java:314)
   at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:268)
   at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:54)
   at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:50)
   at com.raizlabs.android.dbflow.runtime.transaction.process.SaveModelTransaction.processModel(SaveModelTransaction.java:33)
   at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelTransaction$1.processModel(ProcessModelTransaction.java:76)
   at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelHelper$1.run(ProcessModelHelper.java:33)
   at com.raizlabs.android.dbflow.runtime.TransactionManager.transact(TransactionManager.java:108)
   at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelHelper.process(ProcessModelHelper.java:28)
   at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelInfo.processModels(ProcessModelInfo.java:159)
   at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelTransaction.onExecute(ProcessModelTransaction.java:73)
   at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelTransaction.onExecute(ProcessModelTransaction.java:13)
   at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:61)
```

I suspect that it's something related to equipment, since the equipment screen was introduced in that update.
Any help/suggestions for solving this would be greatly appreciated.

**Comment by vIiRuS** [comment]
The biggest issue was due to tags being set wrong when saving a task. So the large amount of crashes should be gone now.
We still have this happen sometimes, so I'll leave this open for now.
