### ISSUE TITLE
Changing the language kills the app

### ISSUE THREAD

**Issue by AlbRoehm** [HabitRPG/habitica-android#695]
When changing the language the app is closed with this error

`FATAL EXCEPTION: TransactionManager
 Process: com.habitrpg.android.habitica.debug, PID: 12578
 java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
 at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:75)
  Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
 at com.magicmicky.habitrpgwrapper.lib.models.HabitRPGUser.save(HabitRPGUser.java:389)
 at com.raizlabs.android.dbflow.runtime.transaction.process.SaveModelTransaction.processModel(SaveModelTransaction.java:33)
 at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelTransaction$1.processModel(ProcessModelTransaction.java:76)
 `...

**Comment by AlbRoehm** [comment]
With the current version (pulled today) the crashes are not reproducible. So this is probably not relevant anymore.
