### ISSUE TITLE
app crashes if the internal memory is full

### ISSUE THREAD

**Issue by ioanb7** [HabitRPG/habitica-android#741]
Hi,

I've had my internal memory maxed out yesterday and the app kept crashing when I entered it.

I might try to look into the issue myself if you want.

Hope it helps,
ioan.

**Comment by vIiRuS** [comment]
Do you mean the ram or the internal storage for data? (I assume the latter)
If you can tell me your habitica user ID (you can find that in the app under Account details in the settings or on the website by opening the API settings from the top right menu) I can check our crash reporting tool for the exception that occured. In case you are having issues replicating the issue, that might help?

**Comment by ioanb7** [comment]
Oh, nice.

My UUID: eeaa2757-fb24-49f9-afbf-1104e94bf70a

**Comment by vIiRuS** [comment]
This is the error. There seem to be some other cases that also cause this crash (that have a more generic "disk I/O Error"), but finding a fix for this should also take care of those.
Considering that there is not much the app can do if it can not create it's database, I'm not sure what the best approach here would be. Probably at least failing gracefully and informing the user as to why the app can't launch.

```
Fatal Exception: java.lang.RuntimeException: android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
       at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:75)
Caused by android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:732)
       at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
       at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
       at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1578)
       at com.raizlabs.android.dbflow.SQLiteCompatibilityUtils.updateWithOnConflict(SQLiteCompatibilityUtils.java:63)
       at com.raizlabs.android.dbflow.sql.SqlUtils.update(SqlUtils.java:289)
       at com.raizlabs.android.dbflow.sql.SqlUtils.save(SqlUtils.java:264)
       at com.raizlabs.android.dbflow.structure.ModelAdapter.save(ModelAdapter.java:54)
       at com.raizlabs.android.dbflow.structure.BaseModel.save(BaseModel.java:50)
       at com.raizlabs.android.dbflow.runtime.transaction.process.SaveModelTransaction.processModel(SaveModelTransaction.java:33)
       at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelTransaction$1.processModel(ProcessModelTransaction.java:76)
       at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelHelper$1.run(ProcessModelHelper.java:33)
       at com.raizlabs.android.dbflow.runtime.TransactionManager.transact(TransactionManager.java:108)
       at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelHelper.process(ProcessModelHelper.java:28)
       at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelInfo.processModels(ProcessModelInfo.java:159)
       at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelTransaction.onExecute(ProcessModelTransaction.java:73)
       at com.raizlabs.android.dbflow.runtime.transaction.process.ProcessModelTransaction.onExecute(ProcessModelTransaction.java:13)
       at com.raizlabs.android.dbflow.runtime.DBTransactionQueue.run(DBTransactionQueue.java:61)
```
