### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object referenc

### ISSUE THREAD

**Issue by phillipthelen** [HabitRPG/habitica-android#93]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
   at com.habitrpg.android.habitica.ui.adapter.HabitItemRecyclerViewAdapter$ViewHolder.bindHolder(HabitItemRecyclerViewAdapter.java:272)
   at com.habitrpg.android.habitica.ui.adapter.HabitItemRecyclerViewAdapter$ChecklistedViewHolder.bindHolder(HabitItemRecyclerViewAdapter.java:384)
   at com.habitrpg.android.habitica.ui.adapter.HabitItemRecyclerViewAdapter$TodoViewHolder.bindHolder(HabitItemRecyclerViewAdapter.java:482)
   at com.habitrpg.android.habitica.ui.adapter.HabitItemRecyclerViewAdapter.onBindViewHolder(HabitItemRecyclerViewAdapter.java:218)
   at com.habitrpg.android.habitica.ui.adapter.HabitItemRecyclerViewAdapter.onBindViewHolder(HabitItemRecyclerViewAdapter.java:58)
   at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:5217)
   at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:5250)
   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4487)
   at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
   at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
   at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
   at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
   at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1161)
   at android.support.v7.widget.LinearLayoutManager.scrollVerticallyBy(LinearLayoutManager.java:1018)
   at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:3807)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
   at android.view.Choreographer.doCallbacks(Choreographer.java:590)
   at android.view.Choreographer.doFrame(Choreographer.java:559)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:145)
   at android.app.ActivityThread.main(ActivityThread.java:5832)
   at java.lang.reflect.Method.invoke(Method.java)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by chandeshwar1791** [comment]
i am getting same error ..how did you solved
